# Identation
vueIndentScriptAndStyle = true

# Wrapping
printWidth = 80
proseWrap = "always"
singleAttributePerLine = false
htmlWhitespaceSensitivity = "css"
embeddedLanguageFormatting = "auto"

# Formating
arrowParens = "always"
bracketSpacing = true
bracketSameLine = false
#embeddedSingleQuote = true
semi = false
singleQuote = false
#singleLineLinkTags = false
trailingComma = "es5"
